-- Find total customers by countries
Select
	Country,
	Count(Customer_number_key) as total_customer
From gold.dim_customer
GROUP BY Country
Order by total_customer
-- Find total customers by gender
Select
	Gender,
	Count(Customer_number_key) as total_customer
From gold.dim_customer
GROUP BY Gender
Order by total_customer
-- Find total products by category
Select 
	Category,
	Count(Product_key) as total_products
From dbo.gold_dim_product
GROUP BY Category
Order by total_products
-- What is the average costs in each category?
Select 
	Category,
	AVG(Product_key) as total_products
From dbo.gold_dim_product
GROUP BY Category
Order by total_products
-- What is the total revenue generated for each category?
Select
	p.Category,
	SUM(f.Sales_Amount) as Total_Sales
From gold.fact_sales as f
LEFT JOIN dbo.gold_dim_product as p
ON p.Product_key = f.Product_key
Group by p.Category
-- Find total revenue is generated by each customer
SELECT
    c.Customer_Number_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customer c
    ON c.Customer_Number_key = f.Customer_Number_key
GROUP BY 
    c.Customer_Number_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.Sales_Quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customer c
    ON c.Customer_Number_key = f.Customer_Number_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
