-- Find total customers by countries
Select
	Country,
	Count(customer_key) as total_customers
From gold.dim_customers
GROUP BY Country
Order by total_customers desc
-- Find total customers by gender
Select
	Gender,
	Count(customer_key) as total_customers
From gold.dim_customers
GROUP BY Gender
Order by total_customers
-- Find total products by category
Select 
	Category,
	Count(Product_key) as total_products
From gold.dim_products
GROUP BY Category
Order by total_products
-- What is the average costs in each category?
Select 
	Category,
	AVG(Product_key) as total_products
From gold.dim_products
GROUP BY Category
Order by total_products
-- What is the total revenue generated for each category?
Select
	p.Category,
	SUM(f.Sales_Amount) as Total_Sales
From gold.fact_sales as f
LEFT JOIN gold.dim_products as p
ON p.Product_key = f.Product_key
Group by p.Category
-- Find total revenue is generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
